#!/usr/bin/env bash

jre/bin/java -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y -classpath bin/skyshard-engine-launcher-0.1.0.jar:bin/felix.jar org.jayware.skyshard.launcher.Launcher